In [1]:
#!pip install tensorflow

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

Matplotlib is building the font cache; this may take a moment.


In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/RahinUlde/DataSets/refs/heads/main/Alphabets_data.csv')
df.head()

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0      T     2     8      3       5      1     8    13      0      6      6   
1      I     5    12      3       7      2    10     5      5      4     13   
2      D     4    11      6       8      6    10     6      2      6     10   
3      N     7    11      6       6      3     5     9      4      6      4   
4      G     2     1      3       1      1     8     6      6      6      6   

   x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0      10       8      0       8      0       8  
1       3       9      2       8      4      10  
2       3       7      3       7      3       9  
3       4      10      6      10      2       8  
4       5       9      1       7      5      10

# Data understanding 

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64 
 2   ybox    20000 non-null  int64 
 3   width   20000 non-null  int64 
 4   height  20000 non-null  int64 
 5   onpix   20000 non-null  int64 
 6   xbar    20000 non-null  int64 
 7   ybar    20000 non-null  int64 
 8   x2bar   20000 non-null  int64 
 9   y2bar   20000 non-null  int64 
 10  xybar   20000 non-null  int64 
 11  x2ybar  20000 non-null  int64 
 12  xy2bar  20000 non-null  int64 
 13  xedge   20000 non-null  int64 
 14  xedgey  20000 non-null  int64 
 15  yedge   20000 non-null  int64 
 16  yedgex  20000 non-null  int64 
dtypes: int64(16), object(1)
memory usage: 2.6+ MB


In [8]:
df.shape

(20000, 17)

In [9]:
df.nunique()

letter    26
xbox      16
ybox      16
width     16
height    16
onpix     16
xbar      16
ybar      16
x2bar     16
y2bar     16
xybar     16
x2ybar    16
xy2bar    16
xedge     16
xedgey    16
yedge     16
yedgex    16
dtype: int64

In [10]:
df['letter'].unique()

array(['T', 'I', 'D', 'N', 'G', 'S', 'B', 'A', 'J', 'M', 'X', 'O', 'R',
       'F', 'C', 'H', 'W', 'L', 'P', 'E', 'V', 'Y', 'Q', 'U', 'K', 'Z'],
      dtype=object)

In [11]:
df['letter'].value_counts()

letter
U    813
D    805
P    803
T    796
M    792
A    789
X    787
Y    786
N    783
Q    783
F    775
G    773
E    768
B    766
V    764
L    761
R    758
I    755
O    753
W    752
S    748
J    747
K    739
C    736
H    734
Z    734
Name: count, dtype: int64

# Encoding (LabelEncoding)

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
# Encode letter labels to integers
le = LabelEncoder()
df['letter'] = le.fit_transform(df['letter'])  # e.g., A=0, B=1, ..., Z=25

In [14]:
df

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
0          19     2     8      3       5      1     8    13      0      6   
1           8     5    12      3       7      2    10     5      5      4   
2           3     4    11      6       8      6    10     6      2      6   
3          13     7    11      6       6      3     5     9      4      6   
4           6     2     1      3       1      1     8     6      6      6   
...       ...   ...   ...    ...     ...    ...   ...   ...    ...    ...   
19995       3     2     2      3       3      2     7     7      7      6   
19996       2     7    10      8       8      4     4     8      6      9   
19997      19     6     9      6       7      5     6    11      3      7   
19998      18     2     3      4       2      1     8     7      2      6   
19999       0     4     9      6       6      2     9     5      3      1   

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0          6      10       8      0       8      0       8  
1         13       3       9      2       8      4      10  
2         10       3       7      3       7      3       9  
3          4       4      10      6      10      2       8  
4          6       5       9      1       7      5      10  
...      ...     ...     ...    ...     ...    ...     ...  
19995      6       6       4      2       8      3       7  
19996     12       9      13      2       9      3       7  
19997     11       9       5      2      12      2       4  
19998     10       6       8      1       9      5       8  
19999      8       1       8      2       7      2       8  

[20000 rows x 17 columns]

# Scaling

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
# Separate indipendent features and target column 
X = df.drop('letter', axis=1)
y = df['letter']

In [17]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [18]:
X_scaled

array([[-1.0576983 ,  0.29187713, -1.05327668, ..., -0.21908163,
        -1.4381527 ,  0.12291107],
       [ 0.51038497,  1.5023577 , -1.05327668, ..., -0.21908163,
         0.12008142,  1.35944092],
       [-0.01230945,  1.19973756,  0.43590966, ..., -0.8656262 ,
        -0.26947711,  0.74117599],
       ...,
       [ 1.03307939,  0.59449727,  0.43590966, ...,  2.36709667,
        -0.65903564, -2.35014863],
       [-1.0576983 , -1.22122359, -0.55688123, ...,  0.42746295,
         0.50963994,  0.12291107],
       [-0.01230945,  0.59449727,  0.43590966, ..., -0.8656262 ,
        -0.65903564,  0.12291107]])

In [19]:
y

0        19
1         8
2         3
3        13
4         6
         ..
19995     3
19996     2
19997    19
19998    18
19999     0
Name: letter, Length: 20000, dtype: int32

# Spliting Data in traning and testing

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
# Split data (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

In [22]:
print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)

Training set size: (16000, 16)
Test set size: (4000, 16)


# Building Model 

In [23]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
# Dense: to add layers(hidden, output)
from tensorflow.keras import Sequential
# Sequential: to add layers in sequence, to initialize ann model i.e. initially random weight will be assigned

In [24]:
# Get number of features and classes
input_dim = X_train.shape[1]
num_classes = len(y.unique())

In [25]:
# Build the model
model = Sequential()
model.add(Dense(units=10, activation='relu', input_shape=(input_dim,)))  # First hidden layer
model.add(Dense(units=num_classes, activation='softmax'))  # Output layer for multiclass

In [26]:
# Compile the model
model.compile(optimizer='adadelta',
              loss='sparse_categorical_crossentropy',  # correct for integer multiclass labels
              metrics=['accuracy'])

In [27]:
# Fit the model
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.1)

Epoch 1/100
450/450 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.0307 - loss: 3.4703 - val_accuracy: 0.0431 - val_loss: 3.4641
Epoch 2/100
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0365 - loss: 3.4516 - val_accuracy: 0.0437 - val_loss: 3.4619
Epoch 3/100
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0311 - loss: 3.4500 - val_accuracy: 0.0444 - val_loss: 3.4596
Epoch 4/100
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0324 - loss: 3.4512 - val_accuracy: 0.0444 - val_loss: 3.4574
Epoch 5/100
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0353 - loss: 3.4541 - val_accuracy: 0.0444 - val_loss: 3.4551
Epoch 6/100
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0366 - loss: 3.4478 - val_accuracy: 0.0444 - val_loss: 3.4528
Epoch 7/100
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0382 - loss: 3.4381 - val_accuracy: 0.0437 - val_loss: 3.4506
Epoch 8/100
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0369 - loss: 3.4500 - val_accu

In [29]:
model.evaluate(X_test, y_test)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0694 - loss: 3.2833


[3.2803943157196045, 0.07000000029802322]

In [30]:
# Predict classes
y_pred_prob = model.predict(X_test)
y_pred_prob
#y_pred_classes = y_pred.argmax(axis=1)  # Get predicted class index

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[0.06388964, 0.02815257, 0.03587206, ..., 0.04532495, 0.03746849,
        0.02819142],
       [0.04075314, 0.03299462, 0.04697474, ..., 0.01987459, 0.04835592,
        0.02392696],
       [0.03549813, 0.05452088, 0.03791682, ..., 0.01998631, 0.03715852,
        0.04080146],
       ...,
       [0.0396196 , 0.04930061, 0.03168811, ..., 0.02943915, 0.04109868,
        0.02927354],
       [0.04312069, 0.018085  , 0.08012687, ..., 0.0178814 , 0.02130149,
        0.05967284],
       [0.0320487 , 0.02972574, 0.09147229, ..., 0.01307131, 0.02472899,
        0.02822188]], dtype=float32)

In [31]:
# Convert probabilities to predicted class labels
y_pred = np.argmax(y_pred_prob, axis=1)

In [32]:
y_pred

array([ 0, 11, 15, ..., 21, 16, 16], dtype=int64)

In [34]:
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.07


In [35]:
print(classification_report(y_test, y_pred, target_names=le.classes_))

              precision    recall  f1-score   support

           A       0.53      0.60      0.56       158
           B       0.00      0.00      0.00       153
           C       0.00      0.00      0.00       147
           D       0.01      0.06      0.02       161
           E       0.00      0.00      0.00       154
           F       0.00      0.00      0.00       155
           G       0.00      0.00      0.00       155
           H       0.00      0.00      0.00       147
           I       0.00      0.00      0.00       151
           J       0.06      0.05      0.05       149
           K       0.01      0.02      0.01       148
           L       0.09      0.05      0.07       152
           M       0.00      0.00      0.00       158
           N       0.00      0.00      0.00       157
           O       0.00      0.00      0.00       150
           P       0.09      0.42      0.15       161
           Q       0.15      0.28      0.19       157
           R       0.01    

# Hyperparameter Tuning using RandomSearchCV

In [40]:
#pip install scikeras

In [41]:
from sklearn.model_selection import RandomizedSearchCV
from scikeras.wrappers import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam, SGD, RMSprop

In [42]:
# Step 1: Wrap model in a function
def create_model(hidden_layers=1, neurons=32, activation='relu', optimizer='adam', learning_rate=0.001):
    model = Sequential()
    model.add(Dense(neurons, activation=activation, input_shape=(X_train.shape[1],)))
    for _ in range(hidden_layers - 1):
        model.add(Dense(neurons, activation=activation))
    model.add(Dense(26, activation='softmax'))  # 26 classes (A-Z)

    if optimizer == 'adam':
        opt = Adam(learning_rate=learning_rate)
    elif optimizer == 'sgd':
        opt = SGD(learning_rate=learning_rate)
    elif optimizer == 'rmsprop':
        opt = RMSprop(learning_rate=learning_rate)

    model.compile(optimizer=opt, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

In [43]:
# Step 2: Create KerasClassifier
model = KerasClassifier(model=create_model, verbose=0)

In [44]:
# Step 3: Define hyperparameter grid
param_dist = {
    'model__hidden_layers': [1, 2],
    'model__neurons': [32, 64, 128],
    'model__activation': ['relu', 'tanh'],
    'model__optimizer': ['adam', 'sgd'],
    'model__learning_rate': [0.01, 0.001],
    'batch_size': [32, 64],
    'epochs': [20]
}

In [45]:
# Step 4: Run RandomizedSearchCV
random_search = RandomizedSearchCV(estimator=model, param_distributions=param_dist, n_iter=5, cv=3, verbose=1, n_jobs=-1)

In [46]:
random_search_result = random_search.fit(X_train, y_train)

Fitting 3 folds for each of 5 candidates, totalling 15 fits


In [47]:
# Step 5: Print best results
print("Best Score:", random_search_result.best_score_)
print("Best Params:", random_search_result.best_params_)

Best Score: 0.9066873391247996
Best Params: {'model__optimizer': 'adam', 'model__neurons': 128, 'model__learning_rate': 0.01, 'model__hidden_layers': 2, 'model__activation': 'tanh', 'epochs': 20, 'batch_size': 32}


# Final model using best parameters

In [48]:
from tensorflow.keras.optimizers import Adam

In [49]:
final_model = Sequential()
final_model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
final_model.add(Dense(64, activation='relu'))  # second hidden layer (since hidden_layers=2)
final_model.add(Dense(26, activation='softmax'))  # output layer for 26 classes

In [50]:
# Compile the model
optimizer = Adam(learning_rate=0.001)  # best optimizer and learning rate
final_model.compile(optimizer=optimizer,
                    loss='sparse_categorical_crossentropy',
                    metrics=['accuracy'])

In [51]:
# Train the model
history = final_model.fit(X_train, y_train,
                          validation_split=0.1,  # keep 10% of training data for validation
                          epochs=20,
                          batch_size=64,
                          verbose=1)

Epoch 1/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.2853 - loss: 2.6480 - val_accuracy: 0.6775 - val_loss: 1.1957
Epoch 2/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7048 - loss: 1.0616 - val_accuracy: 0.7694 - val_loss: 0.8438
Epoch 3/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7752 - loss: 0.7845 - val_accuracy: 0.8025 - val_loss: 0.7006
Epoch 4/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8140 - loss: 0.6352 - val_accuracy: 0.8294 - val_loss: 0.6103
Epoch 5/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8410 - loss: 0.5553 - val_accuracy: 0.8594 - val_loss: 0.5341
Epoch 6/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8524 - loss: 0.4957 - val_accuracy: 0.8731 - val_loss: 0.4824
Epoch 7/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8718 - loss: 0.4446 - val_accuracy: 0.8681 - val_loss: 0.4538
Epoch 8/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8826 - loss: 0.4019 - val_accuracy: 0.

In [52]:
# Predict class probabilities
y_pred_final_probs = final_model.predict(X_test)
y_pred_final_probs

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[2.0459011e-06, 3.9263174e-02, 6.5687001e-13, ..., 1.7199396e-05,
        2.2854167e-10, 4.3356954e-09],
       [3.9645132e-09, 5.0525561e-18, 3.0539612e-15, ..., 1.8151018e-15,
        4.4035340e-13, 1.0714580e-20],
       [7.2198326e-08, 9.9246830e-01, 7.8589121e-11, ..., 4.8142727e-08,
        1.0935532e-08, 3.6170670e-05],
       ...,
       [3.5692648e-07, 4.2533561e-08, 7.3786956e-11, ..., 9.8072219e-01,
        7.9347320e-11, 6.8309872e-11],
       [2.3061625e-08, 1.6380197e-13, 1.7945149e-05, ..., 3.2054128e-08,
        1.8153652e-07, 2.5024850e-12],
       [1.5655367e-12, 6.3803165e-24, 7.0859812e-08, ..., 3.0575414e-15,
        5.2985200e-07, 2.6599069e-22]], dtype=float32)

In [53]:
# Convert probabilities to class indices (0–25)
y_pred_final = np.argmax(y_pred_final_probs, axis=1)

In [54]:
y_pred_final

array([17, 12,  1, ..., 23, 16, 20], dtype=int64)

In [55]:
# Accuracy
accuracy = accuracy_score(y_test, y_pred_final)
print(f"Test Accuracy: {accuracy:.4f}")

Test Accuracy: 0.9313


In [56]:
print(classification_report(y_test, y_pred_final))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97       158
           1       0.86      0.93      0.89       153
           2       0.91      0.99      0.95       147
           3       0.90      0.93      0.91       161
           4       0.90      0.90      0.90       154
           5       0.93      0.91      0.92       155
           6       0.96      0.88      0.92       155
           7       0.94      0.80      0.86       147
           8       0.97      0.89      0.93       151
           9       0.92      0.94      0.93       149
          10       0.90      0.89      0.89       148
          11       0.99      0.93      0.96       152
          12       0.99      0.96      0.97       158
          13       0.93      0.91      0.92       157
          14       0.96      0.91      0.94       150
          15       0.95      0.96      0.95       161
          16       0.94      0.98      0.96       157
          17       0.80    

In [57]:
print(final_model.evaluate(X_train,y_train))
print(final_model.evaluate(X_test,y_test))

500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9501 - loss: 0.1724
[0.18048977851867676, 0.948312520980835]
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9297 - loss: 0.2210
[0.22691349685192108, 0.9312499761581421]
